<a href="https://colab.research.google.com/github/hwanython/SaltLux-machin-learning/blob/main/03_Iris_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 세번째 딥러닝 - 아이리스 품종 분류

아이리스: https://raw.githubusercontent.com/blackdew/ml-tensorflow/master/data/csv/iris.csv

In [ ]:
###########################
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [ ]:
###########################
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

   꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [ ]:
# 원핫인코딩
onehot = pd.get_dummies(아이리스)
onehot.head()

   꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [ ]:
독립 = onehot[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = onehot[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)

In [ ]:
# 모델을 준비합니다. 
X = tf.keras.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.Model(X, Y)
model.compile(loss="categorical_crossentropy", metrics='accuracy')
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_1 (InputLayer)        [(None, 4)]               0

 dense (Dense)               (None, 3)                 15

=================================================================
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________

In [ ]:
# 모델에 데이터를 학습합니다. 
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 6ms/step - loss: 3.2295 - accuracy: 0.3333
Epoch 2/100
5/5 [==============================] - 0s 5ms/step - loss: 3.0705 - accuracy: 0.3333
Epoch 3/100
5/5 [==============================] - 0s 5ms/step - loss: 2.9570 - accuracy: 0.3333
Epoch 4/100
5/5 [==============================] - 0s 4ms/step - loss: 2.8592 - accuracy: 0.3333
Epoch 5/100
5/5 [==============================] - 0s 3ms/step - loss: 2.7665 - accuracy: 0.3333
Epoch 6/100
5/5 [==============================] - 0s 4ms/step - loss: 2.6768 - accuracy: 0.3333
Epoch 7/100
5/5 [==============================] - 0s 3ms/step - loss: 2.5916 - accuracy: 0.3333
Epoch 8/100
5/5 [==============================] - 0s 3ms/step - loss: 2.5078 - accuracy: 0.3333
Epoch 9/100
5/5 [==============================] - 0s 4ms/step - loss: 2.4281 - accuracy: 0.3333
Epoch 10/100
5/5 [==============================] - 0s 6ms/step - loss: 2.3486 - accuracy: 0.3333
Epoch 11/100
5/5 [==============================] - 0s 4ms/step - loss: 2.2733 - accuracy: 0.3333
Epoch 12/100
5/5 [==============================] - 0s 4ms/step - loss: 2.2004 - accuracy: 0.3333
Epoch 13/100
5/5 [==============================] - 0s 4ms/step - loss: 2.1284 - accuracy: 0.3333
Epoch 14/100
5/5 [==============================] - 0s 3ms/step - loss: 2.0602 - accuracy: 0.3333
Epoch 15/100
5/5 [==============================] - 0s 3ms/step - loss: 1.9954 - accuracy: 0.3333
Epoch 16/100
5/5 [==============================] - 0s 3ms/step - loss: 1.9350 - accuracy: 0.3333
Epoch 17/100
5/5 [==============================] - 0s 4ms/step - loss: 1.8775 - accuracy: 0.3333
Epoch 18/100
5/5 [==============================] - 0s 3ms/step - loss: 1.8227 - accuracy: 0.3333
Epoch 19/100
5/5 [==============================] - 0s 3ms/step - loss: 1.7708 - accuracy: 0.3400
Epoch 20/100
5/5 [==============================] - 0s 3ms/step - loss: 1.7221 - accuracy: 0.3667
Epoch 21/100
5/5 [==============================] - 0s 4ms/step - loss: 1.6784 - accuracy: 0.3667
Epoch 22/100
5/5 [==============================] - 0s 5ms/step - loss: 1.6386 - accuracy: 0.3800
Epoch 23/100
5/5 [==============================] - 0s 3ms/step - loss: 1.6007 - accuracy: 0.3933
Epoch 24/100
5/5 [==============================] - 0s 3ms/step - loss: 1.5664 - accuracy: 0.3933
Epoch 25/100
5/5 [==============================] - 0s 4ms/step - loss: 1.5352 - accuracy: 0.3933
Epoch 26/100
5/5 [==============================] - 0s 3ms/step - loss: 1.5042 - accuracy: 0.4200
Epoch 27/100
5/5 [==============================] - 0s 4ms/step - loss: 1.4766 - accuracy: 0.4267
Epoch 28/100
5/5 [==============================] - 0s 3ms/step - loss: 1.4519 - accuracy: 0.4200
Epoch 29/100
5/5 [==============================] - 0s 3ms/step - loss: 1.4267 - accuracy: 0.4267
Epoch 30/100
5/5 [==============================] - 0s 4ms/step - loss: 1.4015 - accuracy: 0.4467
Epoch 31/100
5/5 [==============================] - 0s 3ms/step - loss: 1.3772 - accuracy: 0.4533
Epoch 32/100
5/5 [==============================] - 0s 3ms/step - loss: 1.3545 - accuracy: 0.4600
Epoch 33/100
5/5 [==============================] - 0s 3ms/step - loss: 1.3330 - accuracy: 0.4667
Epoch 34/100
5/5 [==============================] - 0s 4ms/step - loss: 1.3123 - accuracy: 0.4600
Epoch 35/100
5/5 [==============================] - 0s 6ms/step - loss: 1.2924 - accuracy: 0.4667
Epoch 36/100
5/5 [==============================] - 0s 3ms/step - loss: 1.2730 - accuracy: 0.4600
Epoch 37/100
5/5 [==============================] - 0s 4ms/step - loss: 1.2557 - accuracy: 0.4667
Epoch 38/100
5/5 [==============================] - 0s 4ms/step - loss: 1.2392 - accuracy: 0.4733
Epoch 39/100
5/5 [==============================] - 0s 3ms/step - loss: 1.2247 - accuracy: 0.4867
Epoch 40/100
5/5 [==============================] - 0s 3ms/step - loss: 1.2100 - accuracy: 0.4867
Epoch 41/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1959 - accuracy: 0.4867
Epoch 42/100
5/5 [==============================] - 0s 6ms/step - loss: 1.1822 - accuracy: 0.4867
Epoch 43/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1682 - accuracy: 0.4867
Epoch 44/100
5/5 [==============================] - 0s 4ms/step - loss: 1.1560 - accuracy: 0.4867
Epoch 45/100
5/5 [==============================] - 0s 4ms/step - loss: 1.1433 - accuracy: 0.4800
Epoch 46/100
5/5 [==============================] - 0s 4ms/step - loss: 1.1311 - accuracy: 0.4800
Epoch 47/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1194 - accuracy: 0.4800
Epoch 48/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1074 - accuracy: 0.4733
Epoch 49/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0957 - accuracy: 0.4733
Epoch 50/100
5/5 [==============================] - 0s 6ms/step - loss: 1.0843 - accuracy: 0.4800
Epoch 51/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0738 - accuracy: 0.4800
Epoch 52/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0632 - accuracy: 0.4800
Epoch 53/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0531 - accuracy: 0.4800
Epoch 54/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0418 - accuracy: 0.4733
Epoch 55/100
5/5 [==============================] - 0s 6ms/step - loss: 1.0326 - accuracy: 0.4800
Epoch 56/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0219 - accuracy: 0.4800
Epoch 57/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0126 - accuracy: 0.4800
Epoch 58/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0029 - accuracy: 0.4800
Epoch 59/100
5/5 [==============================] - 0s 4ms/step - loss: 0.9925 - accuracy: 0.4800
Epoch 60/100
5/5 [==============================] - 0s 3ms/step - loss: 0.9845 - accuracy: 0.4867
Epoch 61/100
5/5 [==============================] - 0s 4ms/step - loss: 0.9756 - accuracy: 0.4800
Epoch 62/100
5/5 [==============================] - 0s 3ms/step - loss: 0.9667 - accuracy: 0.4733
Epoch 63/100
5/5 [==============================] - 0s 3ms/step - loss: 0.9578 - accuracy: 0.4867
Epoch 64/100
5/5 [==============================] - 0s 5ms/step - loss: 0.9489 - accuracy: 0.5000
Epoch 65/100
5/5 [==============================] - 0s 3ms/step - loss: 0.9409 - accuracy: 0.5200
Epoch 66/100
5/5 [==============================] - 0s 4ms/step - loss: 0.9322 - accuracy: 0.5333
Epoch 67/100
5/5 [==============================] - 0s 3ms/step - loss: 0.9252 - accuracy: 0.5333
Epoch 68/100
5/5 [==============================] - 0s 3ms/step - loss: 0.9172 - accuracy: 0.5533
Epoch 69/100
5/5 [==============================] - 0s 4ms/step - loss: 0.9094 - accuracy: 0.5667
Epoch 70/100
5/5 [==============================] - 0s 3ms/step - loss: 0.9023 - accuracy: 0.5733
Epoch 71/100
5/5 [==============================] - 0s 3ms/step - loss: 0.8948 - accuracy: 0.5800
Epoch 72/100
5/5 [==============================] - 0s 3ms/step - loss: 0.8877 - accuracy: 0.5867
Epoch 73/100
5/5 [==============================] - 0s 4ms/step - loss: 0.8799 - accuracy: 0.6267
Epoch 74/100
5/5 [==============================] - 0s 3ms/step - loss: 0.8749 - accuracy: 0.6200
Epoch 75/100
5/5 [==============================] - 0s 3ms/step - loss: 0.8676 - accuracy: 0.6333
Epoch 76/100
5/5 [==============================] - 0s 4ms/step - loss: 0.8610 - accuracy: 0.6600
Epoch 77/100
5/5 [==============================] - 0s 4ms/step - loss: 0.8547 - accuracy: 0.6733
Epoch 78/100
5/5 [==============================] - 0s 3ms/step - loss: 0.8486 - accuracy: 0.6800
Epoch 79/100
5/5 [==============================] - 0s 3ms/step - loss: 0.8420 - accuracy: 0.6867
Epoch 80/100
5/5 [==============================] - 0s 3ms/step - loss: 0.8357 - accuracy: 0.7067
Epoch 81/100
5/5 [==============================] - 0s 3ms/step - loss: 0.8307 - accuracy: 0.7067
Epoch 82/100
5/5 [==============================] - 0s 4ms/step - loss: 0.8238 - accuracy: 0.7267
Epoch 83/100
5/5 [==============================] - 0s 3ms/step - loss: 0.8182 - accuracy: 0.7267
Epoch 84/100
5/5 [==============================] - 0s 3ms/step - loss: 0.8124 - accuracy: 0.7333
Epoch 85/100
5/5 [==============================] - 0s 3ms/step - loss: 0.8067 - accuracy: 0.7333
Epoch 86/100
5/5 [==============================] - 0s 3ms/step - loss: 0.8016 - accuracy: 0.7333
Epoch 87/100
5/5 [==============================] - 0s 4ms/step - loss: 0.7954 - accuracy: 0.7533
Epoch 88/100
5/5 [==============================] - 0s 3ms/step - loss: 0.7893 - accuracy: 0.7733
Epoch 89/100
5/5 [==============================] - 0s 6ms/step - loss: 0.7845 - accuracy: 0.7800
Epoch 90/100
5/5 [==============================] - 0s 4ms/step - loss: 0.7785 - accuracy: 0.8000
Epoch 91/100
5/5 [==============================] - 0s 4ms/step - loss: 0.7729 - accuracy: 0.8000
Epoch 92/100
5/5 [==============================] - 0s 4ms/step - loss: 0.7672 - accuracy: 0.8067
Epoch 93/100
5/5 [==============================] - 0s 3ms/step - loss: 0.7625 - accuracy: 0.8133
Epoch 94/100
5/5 [==============================] - 0s 4ms/step - loss: 0.7569 - accuracy: 0.8133
Epoch 95/100
5/5 [==============================] - 0s 5ms/step - loss: 0.7514 - accuracy: 0.8133
Epoch 96/100
5/5 [==============================] - 0s 4ms/step - loss: 0.7465 - accuracy: 0.8067
Epoch 97/100
5/5 [==============================] - 0s 4ms/step - loss: 0.7422 - accuracy: 0.8067
Epoch 98/100
5/5 [==============================] - 0s 4ms/step - loss: 0.7370 - accuracy: 0.8200
Epoch 99/100
5/5 [==============================] - 0s 3ms/step - loss: 0.7320 - accuracy: 0.8200
Epoch 100/100
5/5 [==============================] - 0s 4ms/step - loss: 0.7266 - accuracy: 0.8200

In [ ]:
테스트 = 독립.sample(10)
테스트

     꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭
89    5.5  2.5    4.0   1.3
127   6.1  3.0    4.9   1.8
16    5.4  3.9    1.3   0.4
30    4.8  3.1    1.6   0.2
97    6.2  2.9    4.3   1.3
126   6.2  2.8    4.8   1.8
21    5.1  3.7    1.5   0.4
38    4.4  3.0    1.3   0.2
87    6.3  2.3    4.4   1.3
59    5.2  2.7    3.9   1.4

In [ ]:
# 모델을 이용합니다. 
model.predict(테스트)

array([[0.2133866 , 0.40073177, 0.38588163],
       [0.17970435, 0.27721676, 0.54307884],
       [0.6171843 , 0.28920928, 0.09360649],
       [0.49582165, 0.34658262, 0.15759578],
       [0.20411351, 0.4253671 , 0.37051946],
       [0.17959455, 0.3871586 , 0.4332469 ],
       [0.59734005, 0.26689988, 0.13576011],
       [0.5404097 , 0.3102037 , 0.14938657],
       [0.13701938, 0.62594396, 0.23703662],
       [0.24843584, 0.28516462, 0.46639955]], dtype=float32)

In [ ]:
종속.loc[테스트.index, :]

     품종_setosa  품종_versicolor  품종_virginica
22           1              0             0
85           0              1             0
56           0              1             0
31           1              0             0
23           1              0             0
49           1              0             0
146          0              0             1
135          0              0             1
65           0              1             0
98           0              1             0